# Generated by Django 5.1.6 on 2025-03-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_alter_course_options_alter_lesson_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
