# Generated by Django 5.1.6 on 2025-03-25 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0007_subscription_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="owner",
        ),
        migrations.AddField(
            model_name="course",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscribed_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="previews/courses/"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="previews/lessons/"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.CharField(max_length=200),
        ),
    ]
