name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install psycopg2-binary

    - name: Set up PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client
        sudo systemctl start postgresql.service
        sudo -u postgres psql -c "CREATE DATABASE viewset_and_generic_db;"
        sudo -u postgres psql -c "CREATE USER runner WITH PASSWORD 'password' CREATEDB;"
        sudo -u postgres psql -c "ALTER DATABASE viewset_and_generic_db OWNER TO runner;"
        sudo -u postgres psql -d viewset_and_generic_db -c "GRANT ALL PRIVILEGES ON SCHEMA public TO runner;"
        sudo -u postgres psql -d viewset_and_generic_db -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO runner;"
        sudo -u postgres psql -d viewset_and_generic_db -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO runner;"

    - name: Run migrations
      run: |
        export DATABASE_URL=postgresql://runner:password@localhost:5432/viewset_and_generic_db
        python manage.py migrate

    - name: Run tests
      run: |
        export DATABASE_URL=postgresql://runner:password@localhost:5432/viewset_and_generic_db
        python manage.py test
      env:
        SECRET_KEY: "django-insecure-tk&s$q=m7e=w=6=e-smxixln105ih-43edxf+02$ob665%y2dn"
        DEBUG: "True"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'

    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: 158.160.184.103
        username: rilzsnep
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/ViewSet_and_Generetic
          git pull origin dev
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
